"""add start_date to plans

Revision ID: f3d78e4d9067
Revises: ee0b676af6b1
Create Date: 2026-01-22 18:13:00.552346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d78e4d9067'
down_revision: Union[str, Sequence[str], None] = 'ee0b676af6b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1) まず nullable=True で追加
    op.add_column("plans", sa.Column("start_date", sa.Date(), nullable=True))

    # 2) 既存行を埋める（SQLiteのdate('now')を使うと楽）
    op.execute("UPDATE plans SET start_date = date('now') WHERE start_date IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'start_date')
    # ### end Alembic commands ###
